# Generated by Django 4.1.3 on 2022-12-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_Id', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('estate_type', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('rent_sale', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField(default=0)),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('garage', models.IntegerField(default=0)),
                ('sqft', models.IntegerField()),
                ('sold', models.BooleanField(default=False)),
                ('sold_time', models.DateTimeField()),
                ('photo_main', models.ImageField(upload_to='listings_main')),
                ('photo_1', models.ImageField(blank=True, upload_to='listings_1')),
                ('photo_2', models.ImageField(blank=True, upload_to='listings_1')),
                ('photo_3', models.ImageField(blank=True, upload_to='listings_1')),
                ('photo_4', models.ImageField(blank=True, upload_to='listings_1')),
                ('photo_5', models.ImageField(blank=True, upload_to='listings_1')),
                ('photo_6', models.ImageField(blank=True, upload_to='listings_1')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField()),
                ('unless', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
